[tool.poetry]
name = "start-kinesis-app"
version = "0.1.0"
description = ""
authors = ["Raphael Eymann <raphael.eymann@amanox.ch>"]

[tool.poetry.dependencies]
python = "^3.9"
crhelper = "^2.0.11"
aws-lambda-powertools = {extras = ["tracer"], version = "^2.25.1"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
